# Álgebra Linear - Capítulo 4

### Ramo da matemática que lida com espaços vetoriais. 

## Vetores

### Vetores são objetos que podem ser somados juntos e ser multiplicados pelos escalares, formando novos vetores.
### Vetores são pontos em algum espaço de dimensão finita.

In [ ]:
"""
Representar vetores como uma lista de números.
Uma lista de três números corresponde a um vetor em um espaço tridimensional.
"""

hgt_wt_age = [172, # Em cm
              75,  # Em kg
              37]  # Em anos

### Aritmética de Vetores

In [ ]:
import numpy as np
from functools import reduce

# Provavelmente existe uma forma melhor de fazer essas atribuições.
vector_1 = np.random.randint(np.arange(1, 9))
vector_2 = np.random.randint(np.arange(1, 9))
vector_3 = np.random.randint(np.arange(1, 9))
vector_4 = np.random.randint(np.arange(1, 9))

In [ ]:
"""
Dado dois vetores v e w
Somar os elementos correspondentes de cada
v[0] + w[0], v[1] + v[1], ..., v[n] + w[n]
Criando um novo vetor.
"""
def vector_add(v, w):
    return [v_i + w_i for v_i, w_i in zip(v, w)]

print(vector_1)
print(vector_2)

vector_add(vector_1, vector_2)

In [ ]:
"""
Dado dois vetores v e w
Subtrair os elementos correspondentes de cada
v[0] - w[0], v[1] - v[1], ..., v[n] - w[n]
Criando um novo vetor.
"""

def vector_sub(v, w):
    return [v_i - w_i for v_i, w_i in zip(v, w)]

print(vector_1)
print(vector_2)

vector_sub(vector_1, vector_2)

In [ ]:
"""
Dado dois vetores v e w
Multiplicar os elementos correspondentes de cada
v[0] * w[0], v[1] * v[1], ..., v[n] * w[n]
Criando um novo vetor.
"""

def vector_mul(v, w):
    return [v_i * w_i for v_i, w_i in zip(v, w)]

print(vector_1)
print(vector_2)

vector_mul(vector_1, vector_2)

In [ ]:
"""
Somar uma lista de vetores
Criar novo vetor
cujo primeiro elemento seja a soma de todos os primeiros elementos
cujo segundo elemento seja a soma de todos os segundos elementos
e assim por diante.
"""

def vectors_sum(vectors):
    return reduce(vector_add, vectors)

lista_vetores = [vector_1, vector_2, vector_3, vector_4]

print(lista_vetores)

vectors_sum(lista_vetores)

In [ ]:
"""
Multiplicar um vetor por um escalar
Isto é, multiplicar cada elemento de um vetor
por um número x.
"""

def scalar_multiply(v, escalar):
    return [escalar * v_i for v_i in v]

print(vector_1)

escalar = np.random.randint(1, 100)
print(escalar)

scalar_multiply(vector_1, escalar)

In [ ]:
"""
Média de uma lista de vetores
Realizar a soma de vetores, obtendo um novo vetor
Dividir cada elemento deste vetor pelo seu tamanho.
"""

def vectors_mean(vectors):
    return scalar_multiply(vectors_sum(vectors), 1/len(vectors))

print(lista_vetores)
print(vectors_sum(lista_vetores))

vectors_mean(lista_vetores)

In [ ]:
"""
Produto Escalar
Dado dois vetores
Multiplicar seus elementos
v[0] * w[0], v[1] * w[1], ..., v[n] * w[n]
Depois somar cada elemento em um único número.  
"""

def dot(v, w):
    return sum(vector_mul(v, w))

print(vector_1)
print(vector_2)

print(vector_mul(vector_1, vector_2))

dot(vector_1, vector_2)

In [ ]:
"""
Soma dos quadrados de um vetor
Dado um vetor
Aplicar o produto escalar em seus elementos.
"""

def sum_of_squares(v):
    return dot(v, v)

print(vector_1)

sum_of_squares(vector_1)

In [ ]:
"""
Computar a magnitude
Raíz quadrada da soma dos elementos ao quadrado
Calcular a hipotenusa de um vetor
Dentro de um plano cartesiano, dado seus pontos
Seu módulo, tamanho.
"""

from math import sqrt

def magnitude(v):
    return sqrt(sum_of_squares(v))

print(vector_1)

magnitude(vector_1)

In [ ]:
"""
Calcular a distância entre dois vetore
Definida como: √(v1- w1)² + ... (vn - wn)².
"""

def distance_vectors(v, w):
    return magnitude(vector_sub(v, w))

print(vector_1)
print(vector_2)

distance_vectors(vector_1, vector_2)

# Numpy

## Matrizes

### Matriz é uma coleção de números bidimensional.

### Representamos matriz como lista de listas.


In [11]:
import numpy as np


In [12]:
"""
Criando uma matriz 2D
"""
A = np.array([
              [1, 2, 3], 
              [4, 5, 6]
             ])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
"""
Criando uma matriz 2D
Com 2 linhas e 3 colunas
Preenchidas com o número 5.
"""
B = np.full((2, 3), 5)
B

array([[5, 5, 5],
       [5, 5, 5]])

### Soma de Matrizes

In [18]:
"""
Criando 2 matrizes 2D
Somando o elemento de M1[0][0] com M2[0][0]
E assim por diante até M1[1][3] com M2[1][3]
Formando uma única matriz C com a soma.
"""

A = np.array([
    [1, 4, 6, 2],
    [2, 5, 3, 7]
])

B = np.array([
    [9, 6, 4, 8],
    [8, 5, 7, 3]
])

C = A + B
C

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

### Subtração de Matrizes

In [21]:
"""
Utilizando as mesmas matrizes A e B da soma
Apenas mudando o sinal da conta, gerando a matriz C.
"""

C = A - B
C

array([[-8, -2,  2, -6],
       [-6,  0, -4,  4]])

### Produto de Hadamard

In [28]:
"""
Multiplicação de elementos correspondentes
em duas ou mais matrizes com mesmo tamanho.
"""

C = A * B 
C

array([[ 9, 24, 24, 16],
       [16, 25, 21, 21]])